name: Deploy Swipies Website

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to server (with git pull)
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            echo "=== DEPLOY STARTED ==="

            cd ~/landing_swipies
        
            echo "Pull latest changes"
            git reset --hard
            git pull origin main
        
            echo "Set permissions"
            sudo chown -R www-data:www-data ~/landing_swipies
            sudo chmod -R 755 ~/landing_swipies
        
            echo "Restart Nginx"
            sudo systemctl restart nginx
        
            echo "=== DEPLOY FINISHED ==="
